resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:2af6c95f7688c8cc786de7f495949558a8b4572977251c9f9a94451539b03c2b
  name: controller
  newName: registry.redhat.io/rhtas/rhtas-rhel9-operator
