apiVersion: rhtas.redhat.com/v1alpha1
kind: Securesign
metadata:
  labels:
    app.kubernetes.io/name: securesign-sample
    app.kubernetes.io/instance: securesign-sample
    app.kubernetes.io/part-of: trusted-artifact-signer
  name: securesign-sample
  namespace: openshift-rhtas-operator
spec:
  rekor:
    externalAccess:
      enabled: true
    monitoring:
      enabled: true
  trillian:
    database:
      create: true
  fulcio:
    externalAccess:
      enabled: true
    config:
      OIDCIssuers:
        - ClientID: "trusted-artifact-signer"
          IssuerURL: "https://keycloak-keycloak-system.apps.rhamilto.devcluster.openshift.com/auth/realms/trusted-artifact-signer"
          Issuer: "https://keycloak-keycloak-system.apps.rhamilto.devcluster.openshift.com/auth/realms/trusted-artifact-signer"
          Type: "email"
    certificate:
      organizationName: Red Hat
      organizationEmail: jdoe@redhat.com
      commonName: fulcio.hostname
    monitoring:
      enabled: true
  tuf:
    externalAccess:
      enabled: true
  ctlog:
